# Generated by Django 4.2.29 on 2026-03-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
