# Generated by Django 4.2.29 on 2026-03-21 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Reunião'), ('birthday', 'Aniversário'), ('holiday', 'Feriado'), ('shift', 'Turno'), ('training', 'Formação'), ('post', 'Post'), ('mystery_challenge', 'Desafio Mistério'), ('mystery_answer', 'Resposta Mistério'), ('other', 'Outro')], db_index=True, default='meeting', max_length=30)),
                ('is_all_day', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('photo_path', models.CharField(blank=True, default='', max_length=300)),
                ('link', models.URLField(blank=True, default='')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=500)),
                ('event_metadata', models.JSONField(blank=True, default=dict)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthday_events', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='calendar_ev_start_d_930d4c_idx'), models.Index(fields=['event_type'], name='calendar_ev_event_t_fdb766_idx'), models.Index(fields=['restaurant'], name='calendar_ev_restaur_faad81_idx')],
            },
        ),
    ]
