# Generated by Django 4.2.29 on 2026-03-21 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='accounts_em_email_dce3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role'], name='accounts_em_role_9f17cb_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['restaurant'], name='accounts_em_restaur_5c1ad1_idx'),
        ),
    ]
