# Generated by Django 4.2.29 on 2026-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Utilizador', 'verbose_name_plural': 'Utilizadores'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Preferências do utilizador', 'verbose_name_plural': 'Preferências dos utilizadores'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('rh', 'RH'), ('marketing', 'Marketing'), ('administrativa', 'Administrativa'), ('manager', 'Gerente'), ('sub_manager', 'Sub-Gerente'), ('shift_manager', 'Gerente de Turno'), ('treinador', 'Treinador'), ('coucher', 'Coucher'), ('rp', 'Relações Públicas'), ('employee', 'Colaborador')], default='employee', max_length=30),
        ),
    ]
