# Generated by Django 4.2.29 on 2026-03-21 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('upload', 'Upload'), ('download', 'Download'), ('generate', 'Generate'), ('send', 'Send'), ('reset_password', 'Reset Password'), ('status_change', 'Status Change'), ('error', 'Error')], max_length=50)),
                ('description', models.TextField()),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='restaurants.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_activi_user_id_599332_idx'), models.Index(fields=['activity_type', 'created_at'], name='core_activi_activit_e5ffd8_idx'), models.Index(fields=['restaurant', 'created_at'], name='core_activi_restaur_e74fee_idx')],
            },
        ),
    ]
