# Generated by Django 4.2.29 on 2026-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registo de atividade', 'verbose_name_plural': 'Registos de atividade'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Entrada'), ('logout', 'Saída'), ('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Eliminação'), ('view', 'Consulta'), ('upload', 'Carregamento'), ('download', 'Transferência'), ('generate', 'Geração'), ('send', 'Envio'), ('reset_password', 'Reposição da palavra-passe'), ('status_change', 'Alteração de estado'), ('error', 'Erro')], max_length=50),
        ),
    ]
