# Generated by Django 4.2.29 on 2026-03-21 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('birthday', 'Aniversário'), ('praise', 'Elogio'), ('certificate', 'Certificado'), ('memo', 'Memorando'), ('photo', 'Foto'), ('welcome', 'Boas-Vindas'), ('employee_month', 'Funcionário do Mês')], db_index=True, max_length=30)),
                ('template_name', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField(blank=True, default='')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_extension', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generated', 'Gerado'), ('sent', 'Enviado'), ('uploaded', 'Carregado')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='restaurants.restaurant')),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
