# Generated by Django 4.2.29 on 2026-03-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_ssorestaurant_ssouser_alter_worker_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worker',
            table='Colaboradores',
        ),
    ]
