# Generated by Django 4.2.29 on 2026-06-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_worker_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worker',
            table='Usuários',
        ),
    ]
